# Generated by Django 4.1.3 on 2023-02-10 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                blank=True,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Следит за данными авторами",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="this_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
