# Generated by Django 4.1.3 on 2022-12-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_title_photo_alter_article_blogs_and_more'),
        ('users', '0003_rename_tags_profile_blogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='blogs',
            field=models.ManyToManyField(blank=True, to='blog.blog', verbose_name='Следит за данными блогами'),
        ),
    ]
