# Generated by Django 4.1.3 on 2023-01-02 18:15

import blog.services.blog
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_alter_profile_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='', upload_to=blog.services.blog.get_user_directory_path, verbose_name='Фото профиля'),
            preserve_default=False,
        ),
    ]
