# Generated by Django 4.1.3 on 2023-01-03 12:10

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default_profile_picture.jpg', upload_to=users.models.get_user_directory_path, verbose_name='Фото профиля'),
        ),
    ]
