# Generated by Django 4.1.3 on 2023-02-14 14:04

from django.db import migrations
import sorl.thumbnail.fields
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=sorl.thumbnail.fields.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.get_user_directory_path,
                verbose_name="Фото профиля",
            ),
        ),
    ]
