# Generated by Django 4.1.3 on 2023-02-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "Электронная почта уже используется."},
                help_text="Почта должна быть уникальной.",
                max_length=254,
                unique=True,
                verbose_name="Электронный адрес",
            ),
        ),
    ]
