# Generated by Django 4.1.3 on 2023-01-05 14:58

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.get_user_directory_path, verbose_name='Фото профиля'),
        ),
    ]
