# Generated by Django 4.1.3 on 2023-03-10 13:23

from django.conf import settings
from django.db import migrations, models
import sorl.thumbnail.fields
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_alter_language_language"),
        ("users", "0009_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about_me",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="О себе"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="blogs",
            field=models.ManyToManyField(
                blank=True, to="blog.blog", verbose_name="Следит за данными блогами"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                blank=True,
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Следит за данными авторами",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=sorl.thumbnail.fields.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.get_user_directory_path,
                verbose_name="Фото пользователя",
            ),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
