# Generated by Django 4.1.3 on 2023-03-10 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_alter_language_language"),
        ("users", "0010_user_about_me_user_blogs_user_following_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookmarksRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField()),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.article"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="bookmarks",
            field=models.ManyToManyField(
                through="users.BookmarksRelation",
                to="blog.article",
                verbose_name="Закладки",
            ),
        ),
    ]
