# Generated by Django 4.1.3 on 2023-01-25 19:10

import blog.models
import blog.services.blog
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название')),
                ('description', models.CharField(max_length=60, verbose_name='Описание')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='Others', max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Заголовок')),
                ('title_photo', models.ImageField(blank=True, null=True, upload_to=blog.models.get_user_directory_path, verbose_name='Фото')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('body', models.TextField(unique=True, verbose_name='Содержание')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('blogs', models.ManyToManyField(blank=True, to='blog.blog', verbose_name='Блоги')),
                ('language', models.ForeignKey(on_delete=models.SET(blog.services.blog.get_default_language), to='blog.language', verbose_name='Язык')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
