# Generated by Django 4.1.3 on 2022-11-23 17:44

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_language_alter_article_body_alter_article_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.ForeignKey(default=1, on_delete=models.SET(blog.models.get_default_language), to='blog.language', verbose_name='Язык'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author', verbose_name='Автор'),
        ),
    ]
