# Generated by Django 4.1.3 on 2022-12-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_tags_profile_blogs'),
        ('blog', '0003_tag_created_at_tag_description_tag_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Blog',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='tags',
            new_name='blogs',
        ),
    ]
