# Generated by Django 4.1.3 on 2022-12-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='about_yourself',
            field=models.TextField(null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='author',
            name='tags',
            field=models.ManyToManyField(null=True, to='blog.tag', verbose_name='Следит за данными тегами'),
        ),
    ]
