# Generated by Django 4.1.3 on 2022-12-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_tag_blog_rename_tags_article_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title_photo',
            field=models.ImageField(blank=True, upload_to='uploads/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='article',
            name='blogs',
            field=models.ManyToManyField(blank=True, to='blog.blog', verbose_name='Блоги'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Блог'),
        ),
    ]
