# Generated by Django 4.1.3 on 2022-11-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tag_article_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-id']},
        ),
    ]
