# Generated by Django 4.1.3 on 2023-02-18 19:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_article_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={},
        ),
    ]
