# Generated by Django 4.1.3 on 2022-12-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_author_about_yourself_alter_author_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.tag', verbose_name='Следит за данными тегами'),
        ),
    ]
