# Generated by Django 4.1.3 on 2023-02-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_blog_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="language",
            field=models.CharField(default="Не установлен", max_length=16, unique=True),
        ),
    ]
