# Generated by Django 4.1.3 on 2023-02-19 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_language_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="blog.language",
                verbose_name="Язык",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="language",
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
