# Generated by Django 4.1.3 on 2022-12-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_options_alter_author_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='tags',
            field=models.ManyToManyField(to='blog.tag', verbose_name='Теги'),
        ),
    ]
